apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cr7vosspw-nodejs
  janus-idp.io/tekton: cr7vosspw-nodejs
  backstage.io/kubernetes-id: cr7vosspw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cr7vosspw-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
