apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cr7vosspw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cr7vosspw-nodejs 
  name: cr7vosspw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cr7vosspw-nodejs 
